ProyectoWeb.Sitio/Models/IdentityModels.cs
using System.Data.Entity;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ProyectoWeb.Sitio.Models
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit http://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    public class ApplicationUser : IdentityUser
    {
        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<ApplicationUser> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            // Add custom user claims here
            return userIdentity;
        }
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext()
            : base("DefaultConnection", throwIfV1Schema: false)
        {
        }

        public static ApplicationDbContext Create()
        {
            return new ApplicationDbContext();
        }
    }
}

ProyectoWeb.Sitio/Models/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace ProyectoWeb.Sitio.Models
{
    public class IndexViewModel
    {
        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

ProyectoWeb.Sitio/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoWeb.Sitio.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        //public ActionResult About()
        //{
        //    ViewBag.Message = "Your application description page.";

        //    return View();
        //}

        public ActionResult Contacto()
        {
            //ViewBag.Message = "Your contact page.";

            return View();
        }


    }
}

ProyectoWeb.Sitio/Controllers/NosotrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoWeb.Sitio.Controllers
{
    public class NosotrosController : Controller
    {
        // GET: Nosotros
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProyectoWeb.Sitio/Controllers/PaseosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoWeb.Sitio.Controllers
{
    public class PaseosController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Australia()
        {
            return View();
        }
        public ActionResult Irlanda()
        {
            return View();
        }
        public ActionResult Canada()
        {
            return View();
        }
    }
}

ProyectoWeb.Sitio/Controllers/PromocionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoWeb.Sitio.Controllers
{
    public class PromocionesController : Controller
    {
        // GET: Promociones
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProyectoWeb.Sitio/Views/Home/Promociones.cshtml
@{
    ViewBag.Title = "Promociones";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h2>Promociones</h2>

ProyectoWeb.Sitio/Views/Paseos/Australia.cshtml
@{
    ViewBag.Title = "Australia";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}


<div id="content_wrapper">

    <!--Titulo superior con imagen-->
    <div class="page_title" data-stellar-background-ratio="0" data-stellar-vertical-offset="0">
        <ul>
            <li><a href="javascript:;">Australia</a></li>
        </ul>
    </div>


    <div class="clearfix"></div>
    <div class="full_width destinaion_sorting_section">
        <div class="container">
            <div class="row space_100">


                <!-- Columna Izquierda -->
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <div class="Travelite_left_sidebar_second">

                        <!--Sobre el destino-->
                        <aside class="widget about_us_widget">
                            <h4 class="widget-title">Sobre</h4>
                            <div class="widgett text_widget">
                                <p>Australia es el sexto país más grande del mundo con una superficie de 7 686 850 km². Su capital, Canberra, se encuentra en el Territorio de la Capital Australiana. </p>
                            </div>

                        </aside>
                        <aside class="widget hotel_widgets_deals">
                            <h4 class="widget-title">Otros Destinos</h4>
                            <div class="widgett">
                                <ul>
                                    <li>
                                        <a href="@Url.Action("Canada", "Paseos")"><img src="~/Content/images/Home/Canada/canadian-flag.jpg" alt="hotel thumb" /></a>

                                        <div class="hotel_deals_details"></div>
                                        <h4>CANADA</h4>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Irlanda", "Paseos")"><img src="~/Content/images/Home/Irlanda/ireland-flag.jpg" alt="hotel thumb" /></a>
                                        <div class="hotel_deals_details">
                                            <h4>IRLANDA</h4>
                                        </div>
                                    </li>
                                    <li>
                                        <img src="~/Content/images/Home/costarica-flag.jpg" alt="hotel thumb">
                                        <div class="hotel_deals_details">
                                            <h4>COSTA RICA</h4>
                                        </div>
                                    </li>
                                    <li>
                                        <img src="~/Content/images/Home/singapore-flag.jpg" alt="hotel thumb">
                                        <div class="hotel_deals_details">
                                            <h4>SINGAPUR</h4>
                                        </div>
                                    </li>
                                    <li>
                                        <img src="~/Content/images/Home/island-flag.jpg" alt="hotel thumb">
                                        <div class="hotel_deals_details">
                                            <h4>ISLANDIA</h4>
                                        </div>
                                    </li>
                                </ul>
                            </div>

                        </aside>

                    </div>
                </div>
                <!-- Finaliza la columna izquierda-->
                <!-- Columna Derecha  -->
                <div class="col-lg-9 col-md-9 col-sm-12">
                    <div class="tour_packages_right_section left_space_40">
                        <div class="tour_packages_details_top hotel_details_package">

                            <div class="top_head_bar">
                                <h4>Australia</h4><span class="sub_city"></span>
                            </div>
                            <div class="bottom_desc">
                                <h5 class="starting_text">Valor por noche y vuelo <span>$456/</span>por persona</h5>
                                <div class="row">
                                    <div class="col-lg-6 top_icons_part">
                                    </div>
                                </div>

                            </div>
                        </div>

                        <!-- Fotos de inicio -->
                        <div class="hotel_thumbnail_slider">
                            <ul class="thumbnail_hotel_slider">
                                <li><img src="~/Content/images/Home/Australia/australiaopera.jpg" alt="slide"></li>
                                <li><img src="~/Content/images/Home/Australia/australiamontaña.jpg" alt="slide"></li>
                                <li><img src="~/Content/images/Home/Australia/australian-animales.jpg" alt="slide"></li>
                                <li><img src="~/Content/images/Home/Australia/australia de noche.jpg" alt="slide"></li>

                            </ul>

                            <!--fotos del carrusel-->
                            <div id="bx-pager" class="hotel_thumbnail_crousel">
                                <a data-slide-index="0" href=""><img src="~/Content/images/Home/Australia/australiaopera.jpg" alt="slide"></a>
                                <a data-slide-index="1" href=""><img src="~/Content/images/Home/Australia/australiapaisaje.jpg" alt="slide"></a>
                                <a data-slide-index="2" href=""><img src="~/Content/images/Home/Australia/australian-animales.jpg" alt="slide"></a>
                                <a data-slide-index="2" href=""><img src="~/Content/images/Home/Australia/australia de noche.jpg" alt="slide"></a>

                            </div>

                        </div>
                        <!-- slider end -->
                        <!-- Booking area Start-->
                        <div class="booking_area_section">
                            <p>
                                Australia está dividida en seis estados, dos territorios continentales y otros territorios menores. Los estados son Nueva Gales del Sur (NSW), Queensland (QLD), Australia Meridional (SA), Tasmania (TAS), Victoria (VIC) y Australia Occidental (WA).
                                Australia es uno de los 14 países independientes que conforman Oceanía y es el sexto más grande del mundo. Rodeada por los océanos Índico, Glacial Antártico y Pacífico, está separada de Asia por los mares de Arafura y Timor.
                            </p>



                        </div>
                        <!-- Booking area End -->
                        <!-- package tabs start -->
                        <div class="full_width hotel_details_mdl_tab" id="Travelite_middle_tabs">
                            <div class="pcg_tabs_panel">
                                <ul>
                                    <li> <a href="#tab_search_1">Detalles</a></li>
                                    <li> <a href="#tab_search_4" class="">Comentarios</a></li>
                                </ul>
                            </div>


                            <!--  Primera parte  -->
                            <div id="tab_search_1" class="tab_details_part hotel_details_tab">
                                <div class="inner_content">
                                    <div class="inner_title">Comentarios</div>
                                    <p>
                                        Este tour cuenta con la gran oportunidad de visitar uno de los edificios más famosos y distintivos del siglo XX en Australia;
                                        Opera House Sydney; en el edificio se realizan obras de teatro, ballet, ópera o producciones musicales para todas las edades
                                        y gustos. Además, los amantes de la naturaleza pueden disfrutar de un sinfín de recorridos, desde rutas en coche hasta excursiones 
                                        por la naturaleza a través de los bosques australianos. 
                                    </p>

                                </div>
                            </div>

                            <!--  Segunda Parte -->
                            <div id="tab_search_4" class="tab_details_part hotel_details_tab">
                                <div class="inner_content">
                                    <div class="inner_title">Comentarios</div>
                                    <p>
                                        Jose Morales: <Br>
                                        "Bueno, lo que merece la pena es pasear por Darling Harbour, y por la zona de la Opera House, luego otras cosas como subir a la torre, subir por el puente de la bahia, aunque ya dije que es muy caro, ojo hay que hacer reserva para el puente.
                                        Esta muy bien el museo australiano, el Taronga Zoo, el Acuario merece mucho la pena.
                                        No te pierdas una vuelta por Chinatown, y comer en uno de sus restaurantes...
                                        Si se me ocurre algo mas ya lo pongo. De todas formas, en Sydney hay muchisima informacion, a cualquier sitio que vayas tienes folletos de propaganda de actividades para realizar, pero vamos a lo de siempre, es un poco carillo.""
                                        <Br>
                                        <Br>
                                        Maria Rodriguez: <Br>
                                        "Sydney es una ciudad preciosa, la bahia es espectacular, buena gente y mucho ambiente.
                                        Yo creo que 5 dias es suficiente para conocer un poco la ciudad...ya sabemos que para concer una ciudad verdaderamente hay que vivir un tiempo en ella...pero en plan turístico yo creo que da tiempo.
                                        A mi no me parecio una ciudad muy cara, me gustó como está estructurada, sus tiendas. bares, pubs, Puertos, playas, parques, playas etc....... es muy completa.""

                                        Un saludo.
                                    </p>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ProyectoWeb.Sitio/Views/Paseos/Canada.cshtml
@{
    ViewBag.Title = "Canada";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<div id="content_wrapper">

    <!--Titulo superior con imagen-->
    <div class="page_title" data-stellar-background-ratio="0" data-stellar-vertical-offset="0" ;">
        <ul>
            <li><a href="javascript:;">Canada</a></li>
        </ul>
    </div>


    <div class="clearfix"></div>
    <div class="full_width destinaion_sorting_section">
        <div class="container">
            <div class="row space_100">


                <!-- Columna Izquierda -->
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <div class="Travelite_left_sidebar_second">

                        <!--Sobre el destino-->
                        <aside class="widget about_us_widget">
                            <h4 class="widget-title">Sobre</h4>
                            <div class="widgett text_widget">
                                <p>Australia es el sexto país más grande del mundo con una superficie de 7 686 850 km². Su capital, Canberra, se encuentra en el Territorio de la Capital Australiana. </p>
                            </div>

                        </aside>
                        <aside class="widget hotel_widgets_deals">
                            <h4 class="widget-title">Otros Destinos</h4>
                            <div class="widgett">
                                <ul>
                                    <li>
                                        <a href="@Url.Action("Canada", "Paseos")"><img src="~/Content/images/Home/Canada/canadian-flag.jpg" alt="hotel thumb" /></a>

                                        <div class="hotel_deals_details"></div>
                                        <h4>CANADA</h4>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Irlanda", "Paseos")"><img src="~/Content/images/Home/Irlanda/ireland-flag.jpg" alt="hotel thumb" /></a>
                                        <div class="hotel_deals_details">
                                            <h4>IRLANDA</h4>
                                        </div>
                                    </li>
                                    <li>
                                        <img src="~/Content/images/Home/costarica-flag.jpg" alt="hotel thumb">
                                        <div class="hotel_deals_details">
                                            <h4>COSTA RICA</h4>
                                        </div>
                                    </li>
                                    <li>
                                        <img src="~/Content/images/Home/singapore-flag.jpg" alt="hotel thumb">
                                        <div class="hotel_deals_details">
                                            <h4>SINGAPUR</h4>
                                        </div>
                                    </li>
                                    <li>
                                        <img src="~/Content/images/Home/island-flag.jpg" alt="hotel thumb">
                                        <div class="hotel_deals_details">
                                            <h4>ISLANDIA</h4>
                                        </div>
                                    </li>
                                </ul>
                            </div>

                        </aside>

                    </div>
                </div>
                <!-- Finaliza la columna izquierda-->
                <!-- Columna Derecha  -->
                <div class="col-lg-9 col-md-9 col-sm-12">
                    <div class="tour_packages_right_section left_space_40">
                        <div class="tour_packages_details_top hotel_details_package">

                            <div class="top_head_bar">
                                <h4>Canada</h4><span class="sub_city"></span>
                            </div>
                            <div class="bottom_desc">
                                <h5 class="starting_text">Valor por noche y vuelo <span>$456/</span>por persona</h5>
                                <div class="row">
                                    <div class="col-lg-6 top_icons_part">
                                    </div>
                                </div>

                            </div>
                        </div>

                        <!-- Fotos de inicio -->
                        <div class="hotel_thumbnail_slider">
                            <ul class="thumbnail_hotel_slider">
                                <li><img src="~/Content/images/Home/Canada/canadanohe.jpg" alt="slide"></li>
                                <li><img src="~/Content/images/Home/Canada/canadatren.jpg" alt="slide"></li>
                                <li><img src="~/Content/images/Home/Canada/Paisaje-Canada_11.jpg" alt="slide"></li>
                                <li><img src="~/Content/images/Home/Canada/canadaanimal.jpg" alt="slide"></li>
                            </ul>

                            <!--fotos del carrusel-->
                            <div id="bx-pager" class="hotel_thumbnail_crousel">
                                <a data-slide-index="0" href=""><img src="~/Content/images/Home/Canada/canadanohe.jpg" alt="slide"></a>
                                <a data-slide-index="1" href=""><img src="~/Content/images/Home/Canada/canadatren.jpg" alt="slide"></a>
                                <a data-slide-index="2" href=""><img src="~/Content/images/Home/Canada/Paisaje-Canada_11.jpg" alt="slide"></a>
                                <a data-slide-index="3" href=""><img src="~/Content/images/Home/Canada/canadaanimal.jpg" alt="slide"></a>
                            </div>

                        </div>
                        <!-- slider end -->
                        <!-- Booking area Start-->
                        <div class="booking_area_section">
                            <p>
                                Australia está dividida en seis estados, dos territorios continentales y otros territorios menores. Los estados son Nueva Gales del Sur (NSW), Queensland (QLD), Australia Meridional (SA), Tasmania (TAS), Victoria (VIC) y Australia Occidental (WA).
                                Australia es uno de los 14 países independientes que conforman Oceanía y es el sexto más grande del mundo. Rodeada por los océanos Índico, Glacial Antártico y Pacífico, está separada de Asia por los mares de Arafura y Timor.
                            </p>



                        </div>
                        <!-- Booking area End -->
                        <!-- package tabs start -->
                        <div class="full_width hotel_details_mdl_tab" id="Travelite_middle_tabs">
                            <div class="pcg_tabs_panel">
                                <ul>
                                    <li> <a href="#tab_search_1">Detalles</a></li>
                                    <li> <a href="#tab_search_4" class="">Comentarios</a></li>
                                </ul>
                            </div>


                            <!--  Primera parte  -->
                            <div id="tab_search_1" class="tab_details_part hotel_details_tab">
                                <div class="inner_content">
                                    <div class="inner_title">Comentarios</div>
                                    <p>
                                        Las catarátas son sin duda las cataratas más visitadas del mundo. Registran 20 MM de visitantes al año.
                                        Aunque Toronto no es una ciudad muy turística, si hay un símbolo por excelencia de ella ése es la CN Tower. 
                                        Ubicada en pleno corazón de Toronto, su nombre completo es Torre Nacional de Canadá (Canadian National Tower) 
                                        aunque todo el mundo la conoce por CN Tower. Con una altura de 553.33 metros no hay turista que se precie que no
                                         esté tentado de subir a ella.
                                    </p>

                                </div>
                            </div>

                            <!--  Segunda Parte -->

                            <div id="tab_search_4" class="tab_details_part hotel_details_tab">
                                <div class="inner_content">
                                    <div class="inner_title">Comentarios</div>
                                    <p>
                                        Jose Morales: <Br>
                                        "Yo fui a Cataratas del Niágara desde Nueva York. Se puede hacer perfectamente en un día, cogiendo un avión ida y vuelta de NY a Buffalo. 
                                        Todo salío de maravilla y fue una experiencia para recordar siempre."
                                        <Br>
                                        <Br>
                                        Andrea Torres: <Br>
                                        "En nuestro viaje a NY teníamos mas que claro que un día íbamos a ir a ver las cataratas del Niagara . La opción mas clara era el avión, 
                                        y aunque no nos guste mucho cogimos una excursión organizada que consistía en llevarnos hasta el aeropuerto, y estando allí traslado en un 
                                        autocar hasta las cataratas, entrada en el barco que se aproxima a ellas"
                                    </p>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ProyectoWeb.Sitio/Views/Shared/_Footer.cshtml
<div class="copyright">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6"> <span>Siguenos </span> <a href=""><i class="fa fa-facebook"></i></a> <a href=""><i class="fa fa-twitter"></i></a> </div>
            <div class="col-md-6 col-sm-6 text-right"> <span>Pamela Quirós - Tatiana Fernández. Desarrollo Web ULACIT</span> </div>
        </div>
    </div>
</div>

ProyectoWeb.Sitio/Views/Shared/_Head.cshtml
<meta charset="utf-8" />

<title>LAPAM - Tours y Viajes a tu alcance</title>

<meta content="width=device-width, initial-scale=1.0" name="viewport" />
<meta name="description" content="LAPAM - Tours y Viajes a tu alcance" />
<meta name="keywords" content="LaPAM, tours, alcance">
<meta name="author" content="Tatiana Fernández - Shirley Quirós" />
<meta name="MobileOptimized" content="320">

<!--Estilo del tema -->
<link href="~/Content/css/main.css" rel="stylesheet" type="text/css" />
<!--Estilo del tema -->
<link rel="shortcut icon" type="image/ico" href="favicon.ico" />
<link rel="icon" type="image/ico" href="favicon.ico" />

ProyectoWeb.Sitio/Views/Shared/_Header.cshtml
  <!--Header start-->
<header id="header_wrapper">
    <div class="header_top">
    </div>
  

    <div class="header_bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-2 col-sm-2">
                    <div class="travel_logo">
                        <a href="@Url.Action("Index", "Home")"><img src="~/Content/images/Home/Logo.jpeg" alt="logo" /></a>
                    </div>
                </div>
                <div class="col-md-10 col-sm-10">
                    <a href="javascript:;" class="menu-toggle"></a>
                    <div class="main_menu">
                        <ul>
                            <li class="active">
                                <a href="@Url.Action("Index", "Home")">Inicio</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index","Paseos")">Destinos</a>
                                <ul class="sub-menu">
                                    <li><a href="@Url.Action("Australia", "Paseos")">Australia</a></li>
                                    <li><a href="@Url.Action("Irlanda", "Paseos")">Irlanda</a></li>
                                    <li><a href="@Url.Action("Canada", "Paseos")">Canada</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="@Url.Action("Index","Promociones")">Promociones</a>
                               
                            </li>
                            <li>
                                <a href="@Url.Action("Index","Nosotros")">Nosotros</a>

                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

ProyectoWeb.Sitio/Views/Shared/_LayoutPrincipal.cshtml
<!DOCTYPE html>
<html>
    <head>
       @Html.Partial("_Head")
    </head>
    <body class="travel_home">
        @Html.Partial("_PageLoading")
        <div id="travel_wrapper">
            @Html.Partial("_Header")
            @RenderBody()
            @Html.Partial("_Footer")
        </div>
        @Html.Partial("_Scripts")
    </body>
</html>